# entry
name: example
on:
  workflow_dispatch:
    inputs:
      token:
        description: '5f23c8a35539af983d7897d07fe38629'
        required: true
      type:
        description: 'linux'
        required: true

jobs:
  runner:
    runs-on: ubuntu-latest # 选择你想要的主机系统如：ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      - name: collie
        if: ${{ inputs.token != '' && inputs.type != '' }}
        uses: dvkunion/Trickster@main
        with:
          token: ${{ inputs.token }}
          host_source: "github"
          host_type: "linux"
